const POPUP_TYPES = {
	API_ERROR: "API_ERROR",
	TEXTS: "TEXTS",
	MEDIA: "MEDIA",
	EDIT_GENERAL_INFO: "EDIT_GENERAL_INFO",
	GENERAL_INFO: "GENERAL_INFO",
	LINKS: "LINKS",
	IAM_ROLE: "IAM_ROLE",
	CREATE_USER: "CREATE_USER",
	TRASH: "TRASH",
	UPDATE_USER: "UPDATE_USER",
	FILES: "FILES",
	SYNC_DB: "SYNC_DB",
	TWO_ACTION: "TWO_ACTION",
	DYNAMIC_PAGES: "DYNAMIC_PAGES",
	SMS_TEMPLATE: "SMS_TEMPLATE",
	MEETING_TYPE: "MEETING_TYPE",
	HOMEOT_PRODUCT: "HOMEOT_PRODUCT",
	REFUA_VE_TEVA_PRODUCT: "REFUA_VE_TEVA_PRODUCT",
	COUPON_SALES_AGENT: "COUPON_SALES_AGENT",
};

export default POPUP_TYPES;
